# Generated by Django 4.1.4 on 2023-05-13 18:21

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statement', models.FileField(upload_to=tasks.models.overwrite_upload_to)),
            ],
        ),
    ]
