# Generated by Django 4.1.4 on 2023-02-01 19:19

from django.db import migrations, models
import ncba.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=ncba.models.upload_to)),
            ],
        ),
    ]
